# version: "3.8"

services:
  nodejs-app:
    container_name: node-app
    build: ./node-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3001:3000"

volumes:
  prometheus-data: 
