{
 "title": "Instaservice - Accounts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "/account Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "requests_total{api_name=\"/accounts\", env=\"prod\", service_name=\"account-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/accounts Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "duration_seconds_sum{service_name=\"account-service\", api_name=\"/accounts\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "requests_total{api_name=\"/customer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customer_web_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "requests_total{api_name=\"/customer\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}